"""empty message

Revision ID: 671920b400d0
Revises: 
Create Date: 2024-05-07 21:50:59.745326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671920b400d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_id'), 'recommendation', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_user_id'), 'recommendation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_user_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_id'), table_name='recommendation')
    op.drop_table('recommendation')
    # ### end Alembic commands ###
