# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  pull_request:
    branches: ["main"]
    types: [closed]

  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.AWS_ACCESS_SECRET_KEY }} # pem 키
          # 도커 작업
          script: |
            git clone https://github.com/capstone-maru/maru-rec-sys.git
            # docker build --no-cache -t maru-rec-sys-image .
            # docker run -d --name maru-rec-sys-container -p 8000:8000 maru-rec-sys-image
